-- Create a function to access BMR_magwiz data
CREATE OR REPLACE FUNCTION public.get_bmr_magwiz_data()
RETURNS TABLE (
  filename text,
  prefix bigint,
  suffix bigint,
  core_dimension text,
  winding_dimension text,
  backbar_dimension text,
  core_backbar_dimension text,
  side_pole_dimension text,
  sealing_plate_dimension text,
  core_insulator_dimension text,
  conservator_dimension text,
  magnet_dimension text,
  core_mass double precision,
  winding_mass double precision,
  backbar_mass double precision,
  core_backbar_mass double precision,
  side_pole_mass double precision,
  sealing_plate_mass text,
  core_insulator_mass text,
  conservator_mass double precision,
  coolant_mass double precision,
  total_mass double precision,
  belt_width bigint,
  core_size bigint,
  radial_depth bigint,
  coil_height double precision,
  number_of_sections bigint,
  diameter double precision,
  mean_length_of_turn double precision,
  number_of_turns text,
  surface_area double precision,
  wires_in_parallel bigint,
  voltage_A bigint,
  voltage_B double precision,
  voltage_C double precision,
  resistance_A double precision,
  resistance_B double precision,
  resistance_C double precision,
  watts_A bigint,
  watts_B bigint,
  watts_C bigint,
  cold_current_A double precision,
  cold_current_B double precision,
  cold_current_C double precision,
  hot_current_A double precision,
  hot_current_B double precision,
  hot_current_C double precision,
  cold_ampere_turns_A text,
  cold_ampere_turns_B text,
  cold_ampere_turns_C text,
  hot_ampere_turns_A bigint,
  hot_ampere_turns_B bigint,
  hot_ampere_turns_C bigint,
  ambient_temperature_A text,
  ambient_temperature_B text,
  ambient_temperature_C text,
  temperature_rise_A bigint,
  temperature_rise_B bigint,
  temperature_rise_C bigint,
  maximum_rise_A bigint,
  maximum_rise_B bigint,
  maximum_rise_C bigint,
  expected_rise_A double precision,
  expected_rise_B double precision,
  expected_rise_C double precision
)
LANGUAGE SQL
AS $$
  SELECT 
    filename,
    prefix,
    suffix,
    core_dimension,
    winding_dimension,
    backbar_dimension,
    core_backbar_dimension,
    side_pole_dimension,
    sealing_plate_dimension,
    core_insulator_dimension,
    conservator_dimension,
    magnet_dimension,
    core_mass,
    winding_mass,
    backbar_mass,
    core_backbar_mass,
    side_pole_mass,
    sealing_plate_mass,
    core_insulator_mass,
    conservator_mass,
    coolant_mass,
    total_mass,
    belt_width,
    core_size,
    radial_depth,
    coil_height,
    number_of_sections,
    diameter,
    mean_length_of_turn,
    number_of_turns,
    surface_area,
    wires_in_parallel,
    voltage_A,
    voltage_B,
    voltage_C,
    resistance_A,
    resistance_B,
    resistance_C,
    watts_A,
    watts_B,
    watts_C,
    cold_current_A,
    cold_current_B,
    cold_current_C,
    hot_current_A,
    hot_current_B,
    hot_current_C,
    cold_ampere_turns_A,
    cold_ampere_turns_B,
    cold_ampere_turns_C,
    hot_ampere_turns_A,
    hot_ampere_turns_B,
    hot_ampere_turns_C,
    ambient_temperature_A,
    ambient_temperature_B,
    ambient_temperature_C,
    temperature_rise_A,
    temperature_rise_B,
    temperature_rise_C,
    maximum_rise_A,
    maximum_rise_B,
    maximum_rise_C,
    expected_rise_A,
    expected_rise_B,
    expected_rise_C
  FROM "BMR_magwiz";
$$;