// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqhvsdntzgxazcfxqemb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxaHZzZG50emd4YXpjZnhxZW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzQ2ODEsImV4cCI6MjA2MTQxMDY4MX0.MFrwXPaNUnlhtuIn2hSiONeooqgZaIgCtpkoNUzhdqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});